# Generated by Django 2.1 on 2019-06-17 07:57

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_dir',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='employee_dir',
            name='Emp_Email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True, verbose_name='Employee Email'),
        ),
        migrations.AddField(
            model_name='employee_dir',
            name='Emp_city',
            field=models.CharField(max_length=30, null=True, verbose_name='Employee City'),
        ),
        migrations.AddField(
            model_name='employee_dir',
            name='Emp_country',
            field=models.CharField(max_length=30, null=True, verbose_name='Employee Country'),
        ),
        migrations.AddField(
            model_name='employee_dir',
            name='Emp_date_of_joining',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Employee Date of Joining'),
        ),
        migrations.AddField(
            model_name='employee_dir',
            name='Emp_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Employee Phone Number'),
        ),
        migrations.AddField(
            model_name='employee_dir',
            name='Emp_state',
            field=models.CharField(max_length=30, null=True, verbose_name='Employee State'),
        ),
    ]
