# Generated by Django 2.1 on 2019-06-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dir', '0002_auto_20190617_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_dir',
            name='Emp_Increment_Date',
            field=models.DateTimeField(null=True, verbose_name='Employee Date of Increment'),
        ),
        migrations.AddField(
            model_name='employee_dir',
            name='Emp_Salary',
            field=models.IntegerField(null=True, verbose_name='Employee Salary'),
        ),
    ]
