# Generated by Django 2.1 on 2019-06-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dir', '0003_auto_20190617_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_dir',
            name='Emp_Increment_Date',
            field=models.DateField(null=True, verbose_name='Employee Date of Increment'),
        ),
    ]
