# Generated by Django 2.1 on 2019-06-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dir', '0005_auto_20190617_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_dir',
            name='Emp_Increment_Date',
            field=models.DateField(blank=True, null=True, verbose_name='Employee Date of Increment'),
        ),
        migrations.AlterField(
            model_name='employee_dir',
            name='Emp_date_of_joining',
            field=models.DateField(blank=True, null=True, verbose_name='Employee Date of Joining'),
        ),
    ]
